# Generated by Django 6.0.1 on 2026-01-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_alter_agenda_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='expected_finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
