# Generated by Django 6.0.1 on 2026-01-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_agenda_expected_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='expected_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
