# Generated by Django 6.0.1 on 2026-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_agenda_expected_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload relevant files', upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='collaborators',
            field=models.CharField(blank=True, help_text='Comma-separated names of people involved', max_length=255),
        ),
        migrations.AddField(
            model_name='agenda',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to external resources (e.g., Google Doc, Research Paper)'),
        ),
    ]
