# Generated by Django 6.0.1 on 2026-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_agenda_expected_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='assigned_collaborator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
