# Generated by Django 6.0.1 on 2026-01-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_agenda_attachment_agenda_collaborators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institute', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collaborators/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='agenda',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='agendas', to='agendas.collaborator'),
        ),
    ]
