# Generated by Django 6.0.1 on 2026-01-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_agenda_assigned_collaborator'),
        ('agendas', '0007_collaborator_user'),
    ]

    operations = [
    ]
