# Generated by Django 6.0.1 on 2026-01-29 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0008_merge_20260117_1903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='assigned_collaborator',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('agenda_due', 'Agenda Due Soon'), ('agenda_overdue', 'Agenda Overdue'), ('status_change', 'Status Changed'), ('collaborator_added', 'Collaborator Added'), ('agenda_created', 'Agenda Created'), ('agenda_updated', 'Agenda Updated'), ('project_created', 'Project Created')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
