# Generated by Django 6.0.1 on 2026-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0009_remove_agenda_assigned_collaborator_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='category',
            field=models.CharField(blank=True, choices=[('short', 'Short-term'), ('mid', 'Mid-term'), ('long', 'Long-term')], help_text='Manual category override', max_length=20, null=True),
        ),
    ]
