# Generated by Django 6.0.1 on 2026-01-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0010_agenda_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255),
        ),
        migrations.AddField(
            model_name='agenda',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Google Meet link for this task'),
        ),
    ]
