# Generated by Django 6.0.1 on 2026-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0011_agenda_google_event_id_agenda_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting')], default='task', max_length=10),
        ),
    ]
