# Generated by Django 6.0.1 on 2026-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0012_agenda_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('rose', 'Rose'), ('amber', 'Amber'), ('purple', 'Purple'), ('orange', 'Orange'), ('slate', 'Slate')], default='indigo', max_length=20),
        ),
    ]
