# Generated by Django 6.0.1 on 2026-02-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0017_agenda_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_agendas', to='agendas.collaborator'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='division',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='research_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
