# Generated by Django 6.0.1 on 2026-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0018_agenda_team_leader_collaborator_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='actual_participants',
            field=models.ManyToManyField(blank=True, related_name='attended_meetings', to='agendas.collaborator'),
        ),
    ]
