# Generated by Django 5.2.11 on 2026-02-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0022_add_project_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='agendas', through='agendas.AgendaAssignment', to='agendas.collaborator'),
        ),
    ]
