# Generated by Django 6.0.1 on 2026-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0022_add_project_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='extension_count',
            field=models.IntegerField(default=0, help_text='Number of times time has been extended'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='original_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='original_deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='was_missed',
            field=models.BooleanField(default=False, help_text='Flagged if task passed deadline without completion'),
        ),
    ]
