# Generated by Django 6.0.1 on 2026-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0023_agenda_extension_count_agenda_original_deadline_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='extension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='extension_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='agenda',
            name='requested_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='requested_finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
