# Generated by Django 6.0.1 on 2026-02-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0024_agenda_extension_reason_agenda_extension_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='extension_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extensions', to='agendas.collaborator'),
        ),
    ]
