# Generated by Django 6.0.1 on 2026-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0025_agenda_extension_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agenda_due', 'Agenda Due Soon'), ('agenda_overdue', 'Agenda Overdue'), ('status_change', 'Status Changed'), ('collaborator_added', 'Collaborator Added'), ('agenda_created', 'Agenda Created'), ('agenda_updated', 'Agenda Updated'), ('project_created', 'Project Created'), ('time_elapsed_warning', 'Time Elapsed Warning')], max_length=50),
        ),
    ]
