# Generated by Django 6.0.1 on 2026-02-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0026_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='agenda',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='agendas', through='agendas.AgendaAssignment', to='agendas.collaborator'),
        ),
    ]
