# Generated by Django 5.2.11 on 2026-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0023_alter_agenda_collaborators'),
        ('agendas', '0027_alter_agenda_collaborators'),
    ]

    operations = [
    ]
