# Generated by Django 6.0.2 on 2026-02-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0028_merge_20260215_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaassignment',
            name='duties',
            field=models.TextField(blank=True, help_text='Specific duties assigned to this collaborator for this task', null=True),
        ),
    ]
