# Generated by Django 6.0.3 on 2026-03-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0030_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.schedule'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agenda_due', 'Agenda Due Soon'), ('agenda_overdue', 'Agenda Overdue'), ('status_change', 'Status Changed'), ('collaborator_added', 'Collaborator Added'), ('agenda_created', 'Agenda Created'), ('agenda_updated', 'Agenda Updated'), ('project_created', 'Project Created'), ('time_elapsed_warning', 'Time Elapsed Warning'), ('deadline_warning', 'Deadline Warning')], max_length=50),
        ),
    ]
