# Generated by Django 6.0.3 on 2026-03-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0031_notification_related_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
