# Generated by Django 6.0.3 on 2026-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0032_schedule_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
