# Generated by Django 6.0.3 on 2026-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0033_schedule_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agenda_due', 'Agenda Due Soon'), ('agenda_overdue', 'Agenda Overdue'), ('status_change', 'Status Changed'), ('collaborator_added', 'Collaborator Added'), ('agenda_created', 'Agenda Created'), ('agenda_updated', 'Agenda Updated'), ('meeting_invite', 'Meeting Invitation'), ('meeting_updated', 'Meeting Updated'), ('project_created', 'Project Created'), ('time_elapsed_warning', 'Time Elapsed Warning'), ('deadline_warning', 'Deadline Warning'), ('stagnation', 'Task Stagnant')], max_length=50),
        ),
    ]
