# Generated by Django 6.0.3 on 2026-03-14 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0034_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_elapsed_percentage', models.IntegerField(help_text='Auto-calculated percentage of total time elapsed when this was posted')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agenda_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='agendas.agenda')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
