# Generated by Django 6.0.1 on 2026-03-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0035_agendaupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual time taken to complete this task', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated time to complete this task (for Efficiency Score)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='missed_updates',
            field=models.IntegerField(default=0, help_text='Number of missed scheduled updates (for Reliability Score)'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='rework_count',
            field=models.IntegerField(default=0, help_text='Number of times task was sent back for rework (for Reliability Score)'),
        ),
        migrations.AddField(
            model_name='agendaassignment',
            name='composite_score',
            field=models.IntegerField(blank=True, help_text='Overall weighted performance score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='agendaassignment',
            name='efficiency_score',
            field=models.IntegerField(blank=True, help_text='ES: 0-100 calculated from estimated vs actual time', null=True),
        ),
        migrations.AddField(
            model_name='agendaassignment',
            name='quality_score',
            field=models.IntegerField(blank=True, help_text='1-5 rating provided by reviewer', null=True),
        ),
        migrations.AddField(
            model_name='agendaassignment',
            name='reliability_score',
            field=models.IntegerField(blank=True, help_text='RS: 0-100 calculated from reworks and missed updates', null=True),
        ),
        migrations.AddField(
            model_name='agendaassignment',
            name='timeliness_score',
            field=models.IntegerField(blank=True, help_text='TS: 0-100 calculated based on delay penalty', null=True),
        ),
    ]
