# Generated by Django 6.0.3 on 2026-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0037_alter_collaborator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hide from main view while retaining for reference'),
        ),
    ]
