# Generated by Django 6.0.3 on 2026-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0038_agenda_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
