# Generated by Django 6.0.3 on 2026-04-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0039_remove_googletoken_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='related_agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='agendas.agenda'),
        ),
    ]
