# Generated by Django 6.0.3 on 2026-04-11 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0041_taskcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='recipient',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Empty for Group comments', related_name='private_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agenda_due', 'Agenda Due Soon'), ('agenda_overdue', 'Agenda Overdue'), ('status_change', 'Status Changed'), ('collaborator_added', 'Collaborator Added'), ('agenda_created', 'Agenda Created'), ('agenda_updated', 'Agenda Updated'), ('meeting_invite', 'Meeting Invitation'), ('meeting_updated', 'Meeting Updated'), ('project_created', 'Project Created'), ('time_elapsed_warning', 'Time Elapsed Warning'), ('deadline_warning', 'Deadline Warning'), ('stagnation', 'Task Stagnant'), ('comment_added', 'New Task Comment')], max_length=50),
        ),
    ]
