# Generated by Django 6.0.3 on 2026-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0042_remove_taskcomment_recipient_taskcomment_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when status was last set to 'completed'", null=True),
        ),
    ]
