# Generated by Django 6.0.3 on 2026-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0043_agenda_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='task_tag',
            field=models.CharField(blank=True, choices=[('professional_knowledge', 'Professional Knowledge'), ('quality_of_work', 'Quality of Work'), ('devotion_to_duty', 'Devotion to Duty'), ('quantity_of_work_performed', 'Quantity of Work Performed'), ('decision_making_skills', 'Decision-Making Skills'), ('ability_to_implement_decisions', 'Ability to Implement Decisions'), ('supervise_lead_subordinates', 'Capacity to Supervise and Lead Subordinates'), ('teamwork_leadership', 'Capacity for Teamwork, Cooperation, and Leadership'), ('efiling_internet_usage', 'Interest and Proficiency in E-filing and Internet Usage'), ('innovative_work', 'Interest and Capacity for Innovative Work'), ('expression_writing', 'Power of Expression (Writing)'), ('expression_verbal', 'Power of Expression (Verbal)'), ('morality_ethics', 'Morality / Ethics'), ('honesty_integrity', 'Honesty / Integrity'), ('discipline', 'Sense of Discipline'), ('judgment_proportion', 'Judgment and Sense of Proportion'), ('personality', 'Personality'), ('cooperative_attitude', 'Cooperative Attitude'), ('punctuality', 'Punctuality'), ('reliability_dependability', 'Reliability / Dependability'), ('responsibility', 'Sense of Responsibility'), ('interest_attentiveness', 'Interest and Attentiveness in Work'), ('following_instructions', 'Promptness in Following Instructions of Higher Authorities'), ('initiative', 'Initiative'), ('stakeholder_behavior', 'Behavior with Service Recipients / Stakeholders')], help_text='Formal task classification', max_length=100, null=True),
        ),
    ]
