# Generated by Django 6.0.3 on 2026-04-21 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0044_agenda_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='True if created by admin or fully approved'),
        ),
        migrations.AddField(
            model_name='googletoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='googletoken',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='googletoken',
            name='scopes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='googletoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='client_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='client_secret',
            field=models.CharField(default='', max_length=200),
        ),
    ]
